check_api/src/Entity/Serie.php
<?php

namespace App\Entity;

use App\Repository\SerieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SerieRepository::class)]
class Serie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255, unique: true)]
    private ?string $slug = null;

    #[ORM\Column(length: 255)]
    private ?string $poster_url = null;

    #[ORM\Column(length: 255)]
    private ?string $type = null;

    #[ORM\Column(length: 255)]
    private ?string $country = null;

    #[ORM\Column]
    private ?int $release_date = null;

    #[ORM\Column(length: 255)]
    private ?string $platform = null;

    #[ORM\Column]
    private ?int $nb_season = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $synopsis = null;

    #[ORM\Column(length: 255)]
    private ?string $status = null;

    /**
     * @var Collection<int, UserSerie>
     */
    #[ORM\OneToMany(targetEntity: UserSerie::class, mappedBy: 'serie')]
    private Collection $userSeries;

    public function __construct()
    {
        $this->userSeries = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPosterUrl(): ?string
    {
        return $this->poster_url;
    }

    public function setPosterUrl(string $poster_url): static
    {
        $this->poster_url = $poster_url;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): static
    {
        $this->country = $country;

        return $this;
    }

    public function getReleaseDate(): ?int
    {
        return $this->release_date;
    }

    public function setReleaseDate(int $release_date): static
    {
        $this->release_date = $release_date;

        return $this;
    }

    public function getPlatform(): ?string
    {
        return $this->platform;
    }

    public function setPlatform(string $platform): static
    {
        $this->platform = $platform;

        return $this;
    }

    public function getNbSeason(): ?int
    {
        return $this->nb_season;
    }

    public function setNbSeason(int $nb_season): static
    {
        $this->nb_season = $nb_season;

        return $this;
    }

    public function getSynopsis(): ?string
    {
        return $this->synopsis;
    }

    public function setSynopsis(string $synopsis): static
    {
        $this->synopsis = $synopsis;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return Collection<int, UserSerie>
     */
    public function getUserSeries(): Collection
    {
        return $this->userSeries;
    }

    public function addUserSeries(UserSerie $userSeries): static
    {
        if (!$this->userSeries->contains($userSeries)) {
            $this->userSeries->add($userSeries);
            $userSeries->setSerie($this);
        }

        return $this;
    }

    public function removeUserSeries(UserSerie $userSeries): static
    {
        if ($this->userSeries->removeElement($userSeries)) {
            // set the owning side to null (unless already changed)
            if ($userSeries->getSerie() === $this) {
                $userSeries->setSerie(null);
            }
        }

        return $this;
    }
}

check_api/src/Controller/SerieController.php
<?php

namespace App\Controller;

use App\Entity\Serie;
use App\Entity\UserSerie;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\String\Slugger\SluggerInterface;


final class SerieController extends AbstractController
{
    // #[Route('/serie', name: 'app_serie')]
    // public function index(): Response
    // {
    //     return $this->render('serie/index.html.twig', [
    //         'controller_name' => 'SerieController',
    //     ]);
    // }

    // --------------- SHOW ALL SERIEs ---------------
    // #[Route("/", name: "series_index")]
    // public function index(EntityManagerInterface $em): Response
    // {
    //     $series = $em->getRepository(Serie::class)->findAll(); // récupérer toutes les séries
    //     return $this->render('serie/index.html.twig', [
    //         'title' => 'CheckSérieBox',
    //         'series' => $series
    //     ]);
    // }

    #[Route("/", name: "series_index")]
    public function index(EntityManagerInterface $em): Response
    {
        $user = $this->getUser();
        $userSeriesStatus = [];

        if ($user) {
            $userSeries = $em->getRepository(UserSerie::class)->findBy(['user' => $user]);
            foreach ($userSeries as $us) {
                $userSeriesStatus[$us->getSerie()->getId()] = [
                    'list' => $us->getList(), // "watched", "watching", "watchlist", "dropped"
                    'liked' => $us->isLiked() // true / false
                ];
            }
        }

        return $this->render('serie/index.html.twig', [
            'title' => 'CheckSérieBox',
            'series' => $em->getRepository(Serie::class)->findAll(),
            'seriesRandom' => $em->getRepository(Serie::class)->findAllRandom(),
            'userSeriesStatus' => $userSeriesStatus,
            'types' => $em->getRepository(Serie::class)->findDistinctByField('type'),
            'countries' => $em->getRepository(Serie::class)->findDistinctByField('country'),
            'release_dates' => $em->getRepository(Serie::class)->findDistinctByField('release_date'),
            'platforms' => $em->getRepository(Serie::class)->findDistinctByField('platform'),
            'nb_seasons' => $em->getRepository(Serie::class)->findDistinctByField('nb_season'),
            'status' => $em->getRepository(Serie::class)->findDistinctByField('status')
        ]);
    }

    #[Route('/serie/{slug}', name: 'serie_show')]
    public function displaySerie(EntityManagerInterface $em, string $slug): Response
    {
        $serie = $em->getRepository(Serie::class)->findOneBy(["slug" => $slug]);

        if (!$serie) {
            throw $this->createNotFoundException('Série non trouvée');
        }

        return $this->render('serie/serie.html.twig', [
            'title' => 'CheckSérieBox',
            'serie' => $serie
        ]);
    }

    #[Route("/admin/", name: "admin_index")]
    public function admin(EntityManagerInterface $em): Response
    {
        $series = $em->getRepository(Serie::class)->findAll(); // récupérer toutes les séries
        $types = $em->getRepository(Serie::class)->findDistinctByField('type');
        $countries = $em->getRepository(Serie::class)->findDistinctByField('country');
        $release_dates = $em->getRepository(Serie::class)->findDistinctByField('platform');
        $platforms = $em->getRepository(Serie::class)->findDistinctByField('release_date');
        $nb_seasons = $em->getRepository(Serie::class)->findDistinctByField('nb_season');
        $status = $em->getRepository(Serie::class)->findDistinctByField('status');

        return $this->render('serie/admin.html.twig', [
            'title' => 'CheckSérieBox',
            'series' => $series,
            'types' => $types,
            'countries' => $countries,
            'release_dates' => $release_dates,
            'platforms' => $platforms,
            'nb_seasons' => $nb_seasons,
            'status' => $status,
        ]);
    }

    // --------------- ADD A SERIE ---------------
    #[Route("/admin/add", name: "serie_add")]
    public function add(Request $request, EntityManagerInterface $em, SluggerInterface $slugger): Response
    {
        if ($request->isMethod('POST')) {

            // On crée une nouvelle série
            $data = $request->request;
            $serie = new Serie();

            $title = $data->get('title');
            $slug = $slugger
                ->slug($data->get('title'))
                ->lower();

            $serie->setTitle($title);
            $serie->setSlug($slug);
            $serie->setPosterUrl($data->get('poster_url'));
            $serie->setType($data->get('type'));
            $serie->setCountry($data->get('country'));
            $serie->setReleaseDate($data->get('release_date'));
            $serie->setPlatform($data->get('platform'));
            $serie->setNbSeason($data->get('nb_season'));
            $serie->setSynopsis($data->get('synopsis'));
            $serie->setStatus($data->get('status'));

            $em->persist($serie);
            $em->flush();

            return $this->redirectToRoute('series_index', [$this->addFlash('success', 'Votre série a bien été ajoutée !')]); // redirection vers la page principale avec message de succès
        }
        return $this->render('serie/add.html.twig', ['title' => 'CheckSérieBox / Add']); // afficher le formulaire
    }

    // --------------- EDIT A SERIE ---------------
    #[Route("/admin/edit/{id}", name: "serie_edit")]
    public function edit($id, Request $request, EntityManagerInterface $em, SluggerInterface $slugger): Response
    {
        $serie = $em->getRepository(Serie::class)->find($id);
        if (!$serie) {
            throw $this->createNotFoundException('Serie non trouvée');
        }

        if ($request->isMethod('POST')) {

            $data = $request->request;

            $title = $data->get('title');
            $slug = $slugger
                ->slug($data->get('title'))
                ->lower();

            $serie->setTitle($title);
            $serie->setSlug($slug);
            $serie->setPosterUrl($data->get('poster_url'));
            $serie->setType($data->get('type'));
            $serie->setCountry($data->get('country'));
            $serie->setReleaseDate($data->get('release_date'));
            $serie->setPlatform($data->get('platform'));
            $serie->setNbSeason($data->get('nb_season'));
            $serie->setSynopsis($data->get('synopsis'));
            $serie->setStatus($data->get('status'));

            $em->flush(); // mise à jour en bdd

            return $this->redirectToRoute('series_index');
        }

        return $this->render('serie/edit.html.twig', [
            'title' => 'CheckSérieBox / Edit',
            'serie' => $serie
        ]);
    }

    // --------------- DELETE A SERIE ---------------
    #[Route("/admin/delete/{id}", name: "serie_delete")]
    public function delete($id, EntityManagerInterface $em): Response
    {
        $serie = $em->getRepository(Serie::class)->find($id);
        if ($serie) {
            $em->remove($serie);
            $em->flush();
        }
        return $this->redirectToRoute('series_index');
    }


    #[Route('/api/series', name: 'api_series', methods: ['GET'])]
    public function apiSeries(Request $request, EntityManagerInterface $em): JsonResponse
    {
        $filters = [
            'type' => $request->query->get('type'),
            'country' => $request->query->get('country'),
            'release_date' => $request->query->get('release_date'),
            'platform' => $request->query->get('platform'),
            'nb_season' => $request->query->get('nb_season'),
            'status' => $request->query->get('status'),
        ];

        $series = $em->getRepository(Serie::class)->findByFilters($filters);

        return $this->json($series);
    }

}

check_api/templates/serie/add.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ title }} {% endblock %}


{% block body %}

    <style>
        input, textarea {
            width: 100%;
        }
    </style>

    <div class="d-flex justify-content-between align-items-center pb-5">
        <h2>Ajouter une série</h2>
        <a href="{{ path('series_index') }}" class="btn btn-secondary text-white">← Retour à la liste</a>
    </div>

    <form method="POST">
        <div>
            <input type="text" name="title" placeholder="Nom">
        </div>
        <div>
            <input type="url" name="poster_url" placeholder="Poster URL">
        </div>
        <div>
            <select name="type" id="type_select">
                <option>Type</option>
                <option value="Série">Série</option>
                <option value="Mini série">Mini série</option>
                <option value="Web série">Web série</option>
                <option value="Série d'animation">Série d'animation</option>
                <option value="Émission">Émission</option>
                <option value="K-drama">K-drama</option>
                <option value="Anime">Anime</option>
            </select>
        </div>
        <div>
            <input type="text" name="country" placeholder="Pays">
        </div>
        <div>
            <input type="number" name="release_date" placeholder="Date">
        </div>
        <div>
            <input type="text" name="platform" placeholder="Plateforme">
        </div>
        <div>
            <input type="number" name="nb_season" placeholder="Nombre de saisons">
        </div>
        <div>
            <textarea type="text" name="synopsis" placeholder="Synopsis"></textarea>
        </div>
        <div>
            <select name="status" id="status_select">
                <option>Status</option>
                <option value="Finie">Finie</option>
                <option value="Annulée">Annulée</option>
                <option value="En production">En production</option>
                <option value="En cours de diffusion">En cours de diffusion</option>
                <option value="À venir">À venir</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary mt-3">Ajouter</button>
    </form>

{% endblock %}

check_api/templates/serie/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ title }} {% endblock %}

{% block body %}

    <style>
        input, textarea {
            width: 100%;
        }
    </style>

    <div class="d-flex justify-content-between align-items-center pb-5">
        <h2>Modifier la série</h2>
        <a href="{{ path('admin_index') }}" class="btn btn-secondary text-white">← Retour à la liste</a>
    </div>

    <form method="POST">
        <div>
            <input type="text" name="title" value="{{ serie.title }}">
        </div>
        <div>
            <input type="text" name="poster_url" value="{{ serie.posterUrl }}">
        </div>
        <div>
            <select name="type" id="typeSelect">
                <option value={{ serie.type }}>{{ serie.type }}</option>
                <option value="Série">Série</option>
                <option value="Mini série">Mini série</option>
                <option value="Web série">Web série</option>
                <option value="Série d'animation">Série d'animation</option>
                <option value="Émission">Émission</option>
                <option value="K-drama">K-drama</option>
                <option value="Anime">Anime</option>
            </select>
        </div>
        <div>
            <input type="text" name="country" value="{{ serie.country }}">
        </div>
        <div>
            <input type="number" name="release_date" value="{{ serie.releaseDate }}">
        </div>
        <div>
            <input type="text" name="platform" value="{{ serie.platform }}">
        </div>
        <div>
            <input type="number" name="nb_season" value="{{ serie.nbSeason }}">
        </div>
        <div>
            <textarea type="text" name="synopsis">{{ serie.synopsis }}</textarea>
        </div>
        <div>
            <select name="status" id="status_select">
                <option>{{ serie.status }}</option>
                <option value="Finie">Finie</option>
                <option value="Annulée">Annulée</option>
                <option value="En production">En production</option>
                <option value="En cours de diffusion">En cours de diffusion</option>
                <option value="À venir">À venir</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary mt-3">Modifier</button>
    </form>

{% endblock %}

check_api/templates/serie/serie.html.twig
{# {% extends 'base.html.twig' %}

{% block title %}Hello SerieController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code>C:/Users/joann/Documents/GitHub/CheckSerieBox/check_api/src/Controller/SerieController.php</code></li>
        <li>Your template at <code>C:/Users/joann/Documents/GitHub/CheckSerieBox/check_api/templates/serie/index.html.twig</code></li>
    </ul>
</div>
{% endblock %} #}

{% extends 'base.html.twig' %}

{% block title %} {{ title }} {% endblock %}

{% block body %}
    <style>
        li {
            margin: 10px 0;
        }
        .categories li {
            border-bottom: 1px dotted #fff;
            margin-top: 2px;
            width: 12em;
        }
        .infos {
            padding-left: 10px;
        }
        .infos li {
            width: fit-content;
            padding: 0 7px;
            background-color: #707070;
            border-radius: 5px;
        }
        .categories li span {
            line-height: 1.5;
            position: relative;
            top: 7px;
            background-color: rgba(var(--bs-dark-rgb), var(--bs-bg-opacity));
            padding: 1px .2em 0 0;
        }

        .poster-card {
            cursor: pointer;
        }

        .poster-actions {
            bottom: 10px;
            left: 50%;
            transform: translateX(-50%);
            gap: 10px;
            opacity: 0;
            pointer-events: none;
            transition: opacity 0.3s ease;
        }

        .poster-card:hover .poster-actions {
            opacity: 1;
            pointer-events: auto;
        }

        button {
            background-color: transparent;
            border: none;
            padding: auto
        }

        .container {
            margin-top: 150px;
        }
    </style>

    <div class="container mx-auto">
        <div class="row">
            <div class="col-2 position-relative poster-card">
                <div>
                {# <a href="{{ path('serie_show', { slug: serie.slug }) }}" class="text-white"> #}
                    <img src={{ serie.posterUrl }} class="w-100 border rounded" alt={{ serie.slug }} />
                {# </a> #}
                </div>
                <div class="bg-secondary rounded position-absolute poster-actions">
                    <div class="d-flex justify-content-around align-items-center px-2">
                        <button><img src={{ asset('Images/eye.svg') }} style="max-width: 17px" alt="seen" /></button>
                        <button><img src={{ asset('Images/like.svg') }} style="max-width: 17px" alt="like" /></button>
                        <button><img src={{ asset('Images/watchlist.svg') }} style="max-width: 17px" alt="watchlist" /></button>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="d-flex align-items-end gap-3 mb-3">
                    <h1 class="m-0">{{ serie.title }}</h1>
                    <p class="mb-1 underline">{{ serie.releaseDate }}</p>
                </div>
                <p class="mb-5">{{ serie.synopsis }}</p>
            </div>
            <div class="col-4">
                <h3>Détails</h3>
                <div class="d-flex">
                    <ul class="categories p-0">
                        <li><span>Nombre de saison</span></li>
                        <li><span>Pays</span></li>
                        <li><span>Platforme</span></li>
                        <li><span>Type</span></li>
                        <li><span>Status</span></li>
                    </ul>
                    <ul class="infos">
                        <li>{{ serie.nbSeason }}</li>
                        <li>{{ serie.country }}</li>
                        <li>{{ serie.platform }}</li>
                        <li>{{ serie.type }}</li>
                        <li>{{ serie.status }}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>


<script>
</script>

{% endblock %}